spring:
  profiles.active: local
  application.name: hobbyboard
  devtools.livereload.port: 35730
  datasource:
    url: jdbc:h2:tcp://localhost:1521/test
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view:

  h2.console.enabled: false
  sql.init.mode: always
  #redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  mvc.hiddenmethod.filter.enabled: true

  session:
    redis:
      namespace: spring:session